### ISSUE TITLE
Unable to run the tests

### ISSUE THREAD

**Issue by nonomoho** [jhipster/jhipster-vuejs#101]
First I clone the project 
`git clone https://github.com/jhipster/jhipster-vuejs.git`

I run 
`npm install`

I can't run test : `npm test`, I get :
```VueJS JHipster blueprint
    Default with Maven
      1) "before all" hook
    Default with Gradle
      2) "before all" hook
    noi18n with Maven
      3) "before all" hook
    Elasticsearch and Protractor
      4) "before all" hook


  0 passing (873ms)
  4 failing

  1) VueJS JHipster blueprint
       Default with Maven
         "before all" hook:
     Uncaught Error: ERROR! The generator-jhipster-vuejs blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-vuejs.
      at Environment.error (node_modules/yeoman-environment/lib/environment.js:157:40)
      at module.exports.error (node_modules/generator-jhipster/generators/generator-base.js:2444:18)
      at shelljs.exec (node_modules/generator-jhipster/generators/generator-base-private.js:794:22)
      at /Users/arnaudfreismuth/Documents/Ippon/jhipster-vue/jhipster-vuejs/node_modules/shelljs/src/exec.js:124:9
      at ChildProcess.exithandler (child_process.js:301:5)
      at maybeClose (internal/child_process.js:978:16)
      at Socket.stream.socket.on (internal/child_process.js:395:11)
      at Pipe._handle.close (net.js:616:12)
[...]

npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! generator-jhipster-vuejs@0.0.0 test:unit: `mocha --timeout 20000 --slow 0 --reporter spec "test/client.spec.js"`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the generator-jhipster-vuejs@0.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arnaudfreismuth/.npm/_logs/2018-12-06T15_49_25_481Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! generator-jhipster-vuejs@0.0.0 test: `npm run test:unit -- test/*.spec.js`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the generator-jhipster-vuejs@0.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arnaudfreismuth/.npm/_logs/2018-12-06T15_49_25_535Z-debug.log

**Comment by pascalgrimaud** [comment]
You need to install yo: `npm install -g yo`
Thanks @sahbi-ktifa !

**Comment by Senthilkumar-Fullstack** [comment]
> You need to install yo: `npm install -g yo`
> Thanks @sahbi-ktifa !

It works, great!
