### ISSUE TITLE
Followed the install instructions and it isn't working. 

### ISSUE THREAD

**Issue by lfmunoz** [jhipster/jhipster-vuejs#13]
Followed the install instructions and it isn't working. 

Is this a version issue? Please specify in the in the readme which version of jhipster and node it was tested against.

```
$ node -v
v8.12.0

$ npm -v
6.4.1

$ jhipster --version
Using JHipster version installed globally
5.3.4


$ npm i -g generator-jhipster-vuejs                                                                                                                                                                      
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5                                                      
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead                                                                                                              
+ generator-jhipster-vuejs@0.0.3                                                                                                                                                                             
updated 1 package in 23.038s     

$ jhipster --blueprint vuejs


Welcome to JHipster v5.3.4
Application files will be generated in folder: /home/luis/third-party/easy
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! The generator-jhipster-vuejs blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-vuejs.
    at Environment.error (/home/luis/.nvm/versions/node/v10.5.0/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/luis/.nvm/versions/node/v10.5.0/lib/node_modules/generator-jhipster/generators/generator-base.js:2060:18)
    at shelljs.exec (/home/luis/.nvm/versions/node/v10.5.0/lib/node_modules/generator-jhipster/generators/generator-base-private.js:697:26)
    at /home/luis/.nvm/versions/node/v10.5.0/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:124:9
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:595:12)
Emitted 'error' event at:
    at Environment.error (/home/luis/.nvm/versions/node/v10.5.0/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:159:15)
    at module.exports.error (/home/luis/.nvm/versions/node/v10.5.0/lib/node_modules/generator-jhipster/generators/generator-base.js:2060:18)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:595:12)

```

**Comment by lfmunoz** [comment]
tried it with different node versions

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! The generator-jhipster-vuejs blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-vuejs.
    at Environment.error (/home/luis/.nvm/versions/node/v8.12.0/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/home/luis/.nvm/versions/node/v8.12.0/lib/node_modules/generator-jhipster/generators/generator-base.js:2060:18)
    at shelljs.exec (/home/luis/.nvm/versions/node/v8.12.0/lib/node_modules/generator-jhipster/generators/generator-base-private.js:697:26)
    at /home/luis/.nvm/versions/node/v8.12.0/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:124:9
    at ChildProcess.exithandler (child_process.js:283:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
```

**Comment by deepu105** [comment]
This is still work in progress and there is no stable release yet. If you
wanna try it you need to clone the repo and run npm link inside
