### ISSUE TITLE
Error: ERROR! Copying template vue/src/main/webapp/manifest.webapp.ejs failed

### ISSUE THREAD

**Issue by zsliu** [jhipster/jhipster-vuejs#139]
Follow the instruction on the readme.md, I got the following errors. Would you please advise how to resolve it?

Installing languages: en, fr

KeyStore 'src/main/resources/config/tls/keystore.p12' already exists. Leaving unchanged.

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! Copying template vue/src/main/webapp/manifest.webapp.ejs failed. [ReferenceError: /Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/generators/client/templates/vue/src/main/webapp/manifest.webapp.ejs:6
    4|     "icons": [
    5|         {
 >> 6|             "src": "./content/images/<%=hipster%>_head-192.png",
    7|             "sizes": "192x192",
    8|             "type": "image/png"
    9|         },

hipster is not defined]
    at Environment.error (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/node_modules/yeoman-environment/lib/environment.js:157:40)
    at module.exports.error (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base.js:2444:18)
    at ejs.renderFile (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/generators/utils.js:206:23)
    at tryHandleCache (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/ejs/lib/ejs.js:254:14)
    at Object.exports.renderFile (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/ejs/lib/ejs.js:482:10)
    at Object.renderContent (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/generators/utils.js:202:9)
    at module.exports.template (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base-private.js:667:23)
    at blockTemplate.templates.forEach.templateObj (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base.js:2831:42)
    at Array.forEach (<anonymous>)
    at module.exports.writeFilesToDisk (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/generators/generator-base.js:2793:45)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/jliu/dev/git/k8s-dev/saturn1/saturn-new/gateway/jhipster-vuejs/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:427:22)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)

**Comment by pascalgrimaud** [comment]
@sahbi-ktifa : I think we need to give more details about instructions, as I mentionned in the other ticket. I will do it

**Comment by sahbi-ktifa** [comment]
This is due to package-lock in the blueprint repo,  WE should remove it, and then it will be ok with the current instructions

**Comment by pascalgrimaud** [comment]
Which package-lock ? In this repo ?

**Comment by zsliu** [comment]
> Please follow all npm link recommandations, we'll fix this asap.

I followed the readme step by step with npm link already.

> Yes, this one https://github.com/jhipster/jhipster-vuejs/blob/master/package-lock.json

Is there any work around to resolve the issue for now?

**Comment by pascalgrimaud** [comment]
can you try my comment plz ?
https://github.com/jhipster/jhipster-vuejs/issues/131#issuecomment-448660678

**Comment by sahbi-ktifa** [comment]
@zsliu could you update your project and retry ? We made some changes that should prevent this issue and we want to make sure it's ok for you.
