### ISSUE TITLE
CI: migration to Azure

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-vuejs#237]
Vue.js builds failed randomly too frequently. I don't understand why.
I need to check if Azure is better and if it's the case, I will propose to migrate to Azure.

**Comment by pascalgrimaud** [comment]
We have frequently this same logs, so maybe something related to update password:

```
  102 passing (3m)
  5 failing
  1) Account
       should be able to update password:
     WebDriverError: unknown error: Element <li data-v-39b7de9c="" id="account-menu" class="pointer nav-item b-nav-dropdown dropdown router-link-active" href="javascript:void(0);" active-class="active">...</li> is not clickable at point (1199, 31). Other element would receive the click: <div id="login-page" role="dialog" class="modal fade d-block" aria-hidden="true" style="">...</div>
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.45.615279 (12b89733300bd268cff3b78fc76cb8f3a7cc44e5),platform=Linux 4.4.0-101-generic x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:831:22)
      at NavBarPage.<anonymous> (src/test/javascript/e2e/page-objects/navbar-page.ts:122:67)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at /home/travis/app/node_modules/tslib/tslib.js:107:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:103:16)
      at NavBarPage.clickOnAccountMenuItem (src/test/javascript/e2e/page-objects/navbar-page.ts:119:24)
  2) Account
       should be able to log in with new password:
     NoSuchElementError: No element found using locator: By(css selector, .dropdown-menu #login)
      at elementArrayFinder.getWebElements.then (node_modules/protractor/built/element.js:814:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:831:22)
      at NavBarPage.<anonymous> (src/test/javascript/e2e/page-objects/navbar-page.ts:98:30)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at /home/travis/app/node_modules/tslib/tslib.js:107:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:103:16)
      at NavBarPage.clickOnTabMenu (src/test/javascript/e2e/page-objects/navbar-page.ts:92:24)
  3) Account
       should login with user_test account:
     NoSuchElementError: No element found using locator: By(css selector, .dropdown-menu #login)
      at elementArrayFinder.getWebElements.then (node_modules/protractor/built/element.js:814:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:831:22)
      at NavBarPage.<anonymous> (src/test/javascript/e2e/page-objects/navbar-page.ts:98:30)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at /home/travis/app/node_modules/tslib/tslib.js:107:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:103:16)
      at NavBarPage.clickOnTabMenu (src/test/javascript/e2e/page-objects/navbar-page.ts:92:24)
  4) Account
       should be able to change user_test settings:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/travis/app/src/test/javascript/e2e/modules/account/account.spec.ts)
  
  5) Account
       should login with admin account:
     NoSuchElementError: No element found using locator: By(css selector, .dropdown-menu #login)
      at elementArrayFinder.getWebElements.then (node_modules/protractor/built/element.js:814:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)Error
      at ElementArrayFinder.applyAction_ (node_modules/protractor/built/element.js:459:27)
      at ElementArrayFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:91:29)
      at ElementFinder.(anonymous function).args [as click] (node_modules/protractor/built/element.js:831:22)
      at NavBarPage.<anonymous> (src/test/javascript/e2e/page-objects/navbar-page.ts:98:30)
      at step (node_modules/tslib/tslib.js:133:27)
      at Object.next (node_modules/tslib/tslib.js:114:57)
      at /home/travis/app/node_modules/tslib/tslib.js:107:75
      at new Promise (<anonymous>)
      at Object.__awaiter (node_modules/tslib/tslib.js:103:16)
      at NavBarPage.clickOnTabMenu (src/test/javascript/e2e/page-objects/navbar-page.ts:92:24)
[07:12:39] I/launcher - 0 instance(s) of WebDriver still running
[07:12:39] I/launcher - chrome #01 failed 5 test(s)
[07:12:39] I/launcher - overall: 5 failed spec(s)
[07:12:39] E/launcher - Process exited with error code 1
```

**Comment by pascalgrimaud** [comment]
I think I fixed the Protractor tests, so let's close this for now
