### ISSUE TITLE
cannot install jhipster-vuejs

### ISSUE THREAD

**Issue by opensas** [jhipster/jhipster-vuejs#369]
##### **Overview of the issue**

I cannot create a project using the jhipster-vuejs module

These are the steps I tried:

(also tried with npm with similar result)

```shell
$ yarn global add generator-jhipster
yarn global v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "generator-jhipster@6.0.1" with binaries:
      - jhipster
Done in 43.50s.
sas@ubuntu-vb:~/devel/apps/labs/jhipster-vue$ yarn global add generator-jhipster-vuejs
yarn global v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint@^4.19.1 || ^5.3.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-import@^2.14.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.1.1".
warning "generator-jhipster-vuejs > eslint-config-airbnb@17.1.0" has unmet peer dependency "eslint-plugin-react@^7.11.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb > eslint-config-airbnb-base@13.1.0" has unmet peer dependency "eslint@^4.19.1 || ^5.3.0".
warning "generator-jhipster-vuejs > eslint-config-airbnb > eslint-config-airbnb-base@13.1.0" has unmet peer dependency "eslint-plugin-import@^2.14.0".
[4/4] Building fresh packages...
warning "generator-jhipster-vuejs@1.0.0" has no binaries
Done in 12.12s.
sas@ubuntu-vb:~/devel/apps/labs/jhipster-vue$ jhipster --blueprint vuejs
INFO! No custom command found within blueprint: generator-jhipster-vuejs
INFO! Using JHipster version installed globally
INFO! Running default command
INFO! Executing jhipster:app
INFO! Options: blueprint: vuejs, from-cli: true


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.0.1
Application files will be generated in folder: /home/sas/devel/apps/labs/jhipster-vue
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ERROR! The generator-jhipster-vuejs blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-vuejs.
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:1427:18)
    at shelljs.exec (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base-private.js:790:22)
    at /usr/local/lib/node_modules/generator-jhipster/node_modules/shelljs/src/exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
Emitted 'error' event at:
    at Environment.error (/usr/local/lib/node_modules/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:178:15)
    at module.exports.error (/usr/local/lib/node_modules/generator-jhipster/generators/generator-base.js:1427:18)
    [... lines matching original stack trace ...]
    at Pipe._handle.close (net.js:600:12)
```

More info

```shell
$ jhipster info
INFO! Using JHipster version installed globally
INFO! Executing jhipster:info
INFO! Options: from-cli: true
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/home/sas/devel/apps/labs/jhipster-vue
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)

git version 2.20.1

node: v10.15.2

npm: 6.4.1

yarn: 1.16.0

INFO! Congratulations, JHipster execution is complete!
```
```shell
$ uname -a
Linux ubuntu-vb 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by sahbi-ktifa** [comment]
Have you installed the vue.js blueprint ? It seems you did not. Just use:
`npm install -g generator-jhipster-vuejs`

Let us know.

**Comment by pascalgrimaud** [comment]
I think the blueprint has been installed:

```
yarn global add generator-jhipster-vuejs
```

But maybe there is a conflict between npm and yarn, if you tried both installation.

**Comment by ury2000** [comment]
I beat it... !
Just do it in a npm local instalation `npm i generator-jhipster-vuejs`
and then  jhipster --blueprint vuejs
it worked in local installation only .... so very weird

**Comment by sahbi-ktifa** [comment]
Do you mean that installing globally using npm do not work ? It's weird indeed...

**Comment by JaviVargas** [comment]
Same issue here! I'm using npm installation only.

**Comment by hdurix** [comment]
Hi @opensas @ury2000 @JaviVargas. Do you have yeoman installed on your computer?
Check with `npm install -g generator-jhipster`. Yeoman has to be present for blueprints (as opposed to classic JHipster app).

See the correction in the documentation for installing a blueprint : https://github.com/jhipster/jhipster.github.io/pull/742.

**Comment by hdurix** [comment]
Hi @opensas @ury2000 @JaviVargas, do you still experience this issue?

**Comment by jareds** [comment]
@hdurix I ran into this issue on Windows 10 as well. Installing yo fixed it.

**Comment by hdurix** [comment]
Thanks @jareds for your feedback! Then I close the issue.

**Comment by ury2000** [comment]
Hi @hdurix for testing I installed yeoman to use this blueprint and it worked. Thxs

Anyway a few weeks ago I set global npm to install the libraries in $HOME/./npm-global to not use <code> sudo npm install -g generator-jhipster-vuejs </code> cause this issue arose with my sudo installation.  Then it worked too

**Comment by mrts** [comment]
We just experienced the same problem today. Installing `yo` globally didn't help, we had to install everything locally (`generator-jhipster`, `generator-jshipster-vuejs` and `yo`), then it started working.

**Comment by alialperen** [comment]
installing yo solved issue on win10 for me too. Thanks
