### ISSUE TITLE
CI is broken when the jhipster-vuejs is not aligned on the generator-jhipster version

### ISSUE THREAD

**Issue by clementdessoude** [jhipster/jhipster-vuejs#469]
##### **Overview of the issue**

CI is broken. All last builds failed on jhipster info with same error
```
Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/vsts/generator-jhipster/cli/jhipster.js:20:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
see: https://dev.azure.com/jhipster/jhipster-vuejs/_build?definitionId=7

##### **Motivation for or Use Case**

Have a reliable CI to be limit bugs introductions

##### **Reproduce the error**

N/A

##### **Suggest a Fix**

I think it is coming from the links, and that npm flattens the librairies when `npm ci` or `npm install` is run.
I made a fix, but I think we can do better.

##### **JHipster configuration**
N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
N/A

##### **Browsers and Operating System**
N/A

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by clement26695** [comment]
For the moment, all the builds target the generator-jhipster master branch ? Should me move this to the latest supported generator-jhipster version ?

We could add a branch (e.g. develop) which would target master to integrate some other changes

**Comment by pascalgrimaud** [comment]
I already discussed about it with @sahbi-ktifa few months ago.
We decided to keep the development as simple as possible, to avoid maintaining 2 branchs as we do with jhipster-registry

So for now, I think we should keep thing simple and only use 1 branch (master), linked to master branch of generator-jhipster

I'll add the upgrade of package.json in the process of release of generator-jhipster

**Comment by pascalgrimaud** [comment]
For now, the best workflow is to upgrade manually the package.json
Not sure we can do better...
