### ISSUE TITLE
Runs well but error when build.

### ISSUE THREAD

**Issue by yingw** [jhipster/jhipster-vuejs#52]
The link version of this blueprint works well when run in dev mode, but fail when `npm run build` or `mvn -P prod clean package`

it says

```
[INFO] > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.prod.js" "--profile"
[INFO] 
[ERROR] sh: line 1:  3259 Killed                  npm run webpack:prod:main
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 137
[ERROR] npm ERR! jhipster@0.0.0 webpack:prod: `npm run cleanup && npm run webpack:prod:main && npm run clean-www`
[ERROR] npm ERR! Exit status 137
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the jhipster@0.0.0 webpack:prod script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /root/.npm/_logs/2018-11-23T05_34_15_302Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:16 min
[INFO] Finished at: 2018-11-23T13:34:15+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (webpack build prod) on project jhipster: Failed to run task: 'npm run webpack:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 137 (Exit value: 137) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

and in the log file:  /root/.npm/_logs/2018-11-23T05_34_15_302Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/root/jhipster/vue/my-app/node/node',
1 verbose cli   '/root/jhipster/vue/my-app/node/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'webpack:prod' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prewebpack:prod', 'webpack:prod', 'postwebpack:prod' ]
5 info lifecycle jhipster@0.0.0~prewebpack:prod: jhipster@0.0.0
6 info lifecycle jhipster@0.0.0~webpack:prod: jhipster@0.0.0
7 verbose lifecycle jhipster@0.0.0~webpack:prod: unsafe-perm in lifecycle true
8 verbose lifecycle jhipster@0.0.0~webpack:prod: PATH: /root/jhipster/vue/my-app/node/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/jhipster/vue/my-app/node_modules/.bin:/root/jhipster/vue/my-app/node:/usr/lib64/qt-3.3/bin:/opt/node/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:
9 verbose lifecycle jhipster@0.0.0~webpack:prod: CWD: /root/jhipster/vue/my-app
10 silly lifecycle jhipster@0.0.0~webpack:prod: Args: [ '-c',
10 silly lifecycle   'npm run cleanup && npm run webpack:prod:main && npm run clean-www' ]
11 silly lifecycle jhipster@0.0.0~webpack:prod: Returned: code: 137  signal: null
12 info lifecycle jhipster@0.0.0~webpack:prod: Failed to exec webpack:prod script
13 verbose stack Error: jhipster@0.0.0 webpack:prod: `npm run cleanup && npm run webpack:prod:main && npm run clean-www`
13 verbose stack Exit status 137
13 verbose stack     at EventEmitter.<anonymous> (/root/jhipster/vue/my-app/node/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/root/jhipster/vue/my-app/node/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid jhipster@0.0.0
15 verbose cwd /root/jhipster/vue/my-app
16 verbose Linux 3.10.0-862.14.4.el7.x86_64
17 verbose argv "/root/jhipster/vue/my-app/node/node" "/root/jhipster/vue/my-app/node/node_modules/npm/bin/npm-cli.js" "run" "webpack:prod"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 137
22 error jhipster@0.0.0 webpack:prod: `npm run cleanup && npm run webpack:prod:main && npm run clean-www`
22 error Exit status 137
23 error Failed at the jhipster@0.0.0 webpack:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 137, true ]
```

**Comment by yingw** [comment]
It should say: 

The `npm run cleanup && npm run webpack:build:main` works find, and generated correct `www/index.html` files and js. But build with profile (such as prod) will fail like said before.

**Comment by pascalgrimaud** [comment]
I didn't test the build in prod. But as it is still in development, I'm not surprised.
Help is welcome, if you know how it can be fixed!

**Comment by sahbi-ktifa** [comment]
Are you up to date? As we fixed prod build few days ago!
 Is it a simple application or did you already add specific code ?

**Comment by yingw** [comment]
@sahbi-ktifa yes, guys, I update the latest blueprint and everything works now, Thanks for your efforts on this.

But btw there is another tiny issue, the define in pom needs `webpack:test` execution and there is none of this define in `package.json`, **I just delete the "webpack build test" in pom, then everything works.**

I tested:
`mvn package` to build dev env.
`mvn -Pprod clean package -Dmaven.test.skip=true` to build prod. Both works.

Thanks again! 😄

**Comment by fil512** [comment]
I am really suffering from this issue and can't move forward.  @yingw what do you mean when you said you update the latest blueprint?  Is this something I can do to?

Thanks!
Ken

**Comment by pascalgrimaud** [comment]
@fil512 : can you provide your information about your project, using `jhipster info` and all steps to reproduce ?
Better, you could push a project on github, so we'll be able to try to reproduce.
