### ISSUE TITLE
Error generating enumeration type fields with entity generator command line

### ISSUE THREAD

**Issue by yuniel-acosta** [jhipster/jhipster-vuejs#627]
##### **Overview of the issue**

Error generating enumeration type fields with command line entity generator. After updating the generator to the latest versions, I create a new project I have tried to add an entity from the command line 'jhipster entity NameEntity' and adding a field that is of type enumeration does not allow me to create the enumeration and when trying to create the entity throws the following error at me
  ```
The entity UserExtra is being created.

? Do you want to generate this entity from an existing microservice? No

Generating field #1

? Do you want to add a field to your entity? Yes
? What is the name of your field? gender
? What is the type of your field? Enumeration (Java enum type)
? Do you want to add validation rules to your field? No

================= UserExtra =================
Fields
gender (enum) 


Generating field #2

? Do you want to add a field to your entity? No

================= UserExtra =================
Fields
gender (enum) 


Generating relationships to other entities

? Do you want to add a relationship to another entity? No

================= UserExtra =================
Fields
gender (enum) 



? Do you want to use separate service class for your business logic? Yes, generate a separate
 service class
? Do you want to use a Data Transfer Object (DTO)? Yes, generate a DTO with MapStruct
? Do you want to add filtering? Not needed
? Is this entity read-only? No
? Do you want pagination on your entity? Yes, with infinite scroll

Everything is configured, generating the entity...

WARNING! changelogDate is missing in .jhipster/UserExtra.json, using 20200603133105 as fallback
     info Using blueprint generator-jhipster-vuejs for entity-client subgenerator
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: Copying template /home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs failed. [TypeError: /home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs:19
    17|  limitations under the License.
    18| -%>
 >> 19| <%_
    20| let table = [];
    21| 
    22| // Generate CSV header

Cannot read property 'length' of undefined]
    at module.exports.error (/home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/generator-base.js:1590:15)
    at /home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/utils.js:256:23
    at tryHandleCache (/home/acosta/Desktop/serf/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:275:14)
    at Object.exports.renderFile (/home/acosta/Desktop/serf/node_modules/generator-jhipster/node_modules/ejs/lib/ejs.js:478:10)
    at Object.renderContent (/home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/utils.js:252:9)
    at module.exports.template (/home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/generator-base-private.js:769:23)
    at /home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/generator-base.js:2040:42
    at Array.forEach (<anonymous>)
    at module.exports.writeFilesToDisk (/home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/generator-base.js:2002:45)
    at module.exports.writeServerFiles (/home/acosta/Desktop/serf/node_modules/generator-jhipster/generators/entity-server/files.js:345:18)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/home/acosta/Desktop/serf/node_modules/yeoman-generator/lib/index.js:924:20)

```

##### **Reproduce the error**
Create a new project and try to generate a new entity with the command line `jhipster entity NameEntity` and add a new field Enumeration

##### **JHipster Version(s)**
jhipster-generator v6.9.1
jhipster-generator-vuejs v1.8.2

##### **JHipster configuration**
```

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test",
      "nativeLanguage": "es"
    },
    "jhipsterVersion": "6.9.1",
    "applicationType": "gateway",
    "baseName": "test",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "gradle",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "Your Secrect Key",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "yarn",
    "clientFramework": "vue",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1591070127581,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.8.2"
      }
    ],
    "enableTranslation": true,
    "nativeLanguage": "es",
    "languages": ["es", "en"],
    "blueprints": [
      {
        "name": "generator-jhipster-vuejs",
        "version": "1.8.2"
      }
    ]
  }
}
```

##### **Browsers and Operating System**
Chrome Version 80.0.3987.149 (Official Build) (64-bit)
Brave Version 1.9.68 Chromium: 81.0.4044.138 (Official Build) unknown (64-bit)
OS: Manjaro 5.6.15-1-MANJARO

-   [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Thanks for reporting this, @yuniel-acosta : I can confirm the issue
